expose_php = Off
memory_limit = 256M
upload_max_filesize = 32M
post_max_size = 40M
opcache.enable = 1
opcache.validate_timestamps = 0
opcache.memory_consumption = 128
opcache.max_accelerated_files = 20000
